Feature2021/2/5 create landing page
tanakafumiaki/self-introduction pull request #10
Opened 2021-02-05 08:23 UTC by tanakafumiaki

Landingページを作成いたしました。

2021-02-07 07:51 UTC, tsurutan requested changes

2021-02-07 07:51 UTC, tsurutan commented on pages/index.tsx
> +        <button className={styles.button}>
[imo]
こちらをAtomic Designに沿ってコンポーネント分解してみましょう。

`src/components/atoms/PrimaryButton/index.tsx`
`src/components/atoms/PrimaryButton/styles.sass`

のようにファイルをまとめ、この pageでは `PrimaryButton` を

```
<PrimaryButton
  href="/selection"
  text="Click" />
```

というように使うことができれば再利用性があがり、運用保守が楽になると思います。

2021-02-07 07:51 UTC, tsurutan commented on pages/_app.tsx
> +import '../styles/globals.scss'
[imo]
TypeScript周りで自分で作成するファイルは `src` ディレクトリでまとめましょう

例
`src/pages/_app.tsx` など

2021-02-07 07:51 UTC, tsurutan commented on styles/Home.module.scss
> +.main {
[imo]
スタイルは `コンポーネントディレクトリ/styles.sass` のように書くようにしましょう。
そうすることでファイルとスタイルの距離が近くなり管理しやすくなります。
またscssよりsassを使うと `{` を省略できるのでおすすめです。

2021-02-07 07:51 UTC, tsurutan commented on styles/Home.module.scss
> +  width: 260px;
[imo]
px だとデバイスの幅が変わっても固定されてしまうので、幅・高さなどデバイスの幅で変えたいものは `rem` を単位で使用すると良いです。

2021-02-10 02:32 UTC, tsurutan requested changes

2021-02-10 02:32 UTC, tsurutan commented on src/components/atoms/PrimaryButton/index.tsx
> +interface PrimaryButtonProps {
[imo]
このファイルの中でPropsは PrimaryButton しかないと思うので  `Props` という名前で良いかと思います。

2021-02-10 02:32 UTC, tsurutan commented on src/components/atoms/PrimaryButton/index.tsx
> +export default function PrimaryButton(props: PrimaryButtonProps) {
[imo]
このまま関数宣言でも良いのですがアロー関数を使用し `React.VFC` という型を付けると、関数コンポーネントの方がつくのでおすすめです。
また下記のようにPropsは分割代入で使用するようにすると簡潔に書けます。

```ts
const PrimaryButton: React.VFC = ({ link, text }: Props) => {}
```

2021-02-10 02:32 UTC, tsurutan commented on src/components/atoms/PrimaryButton/style.module.sass
> +    background-color: #78A5E2
[imo]
色など他の箇所でも使用する値は、変数として一つのファイルに纏めたほうが管理しやすくなります。

`src/components/global.module.sass` に

```sass
$green: #123123
```

のような感じで色に関する変数を作成し、この色を読み込むところで

```sass
@import "../../global.module.sass"

.button
  color: $green
```

のように書くとメンテナンスしやすくなると思います。

(上の例はそのまま書いても動かない可能性があるので、適宜修正してください)

2021-02-11 07:14 UTC, tsurutan requested changes

2021-02-11 07:14 UTC, tsurutan commented on src/components/atoms/PrimaryButton/style.module.sass
> +    a
この `a` は必要でしょうか？

2021-02-11 07:14 UTC, tsurutan commented on src/components/atoms/PrimaryButton/index.tsx
> +                <a className={styles.p}>{text}</a>
[ask]
pクラスは作成していますでしょうか？

2021-02-11 07:14 UTC, tsurutan commented on src/components/atoms/PrimaryButton/style.module.sass
> +      padding-top: 38%
[imo]
ファイルの末尾に改行を入れましょう。
改行を入れないと禁止マークのようなアイコンが表示されます。
他ファイルも対応お願いします。

2021-02-11 08:17 UTC, tanakafumiaki commented
PrimaryButton/style.module.sass内のaは必要がないため削除いたしました。
また、PrimaryButton/index.tsx内のpクラスも必要ないため削除いたしました。
ファイルの末尾に改行を追加いたしました。

2021-02-12 09:42 UTC, tsurutan requested changes

2021-02-12 09:42 UTC, tsurutan commented on src/pages/index.tsx
> +export default function Home() {
[imo]
こちらも アロー関数で書きましょう。

2021-02-12 09:42 UTC, tsurutan commented on src/pages/index.tsx
> +import PrimaryButton from "../components/atoms/PrimaryButton";
[imo]
tsconfig.json で baseUrl を指定することでインポート文を絶対パスでしていすることができるので、こちらに変更しましょう。

2021-02-12 09:42 UTC, tsurutan commented on src/pages/index.tsx
> +import PrimaryButton from "../components/atoms/PrimaryButton";
[imo]
今の書き方だと、仮に複数のコンポーネントをインポートするとき

```
import PrimaryButton from "../components/atoms/PrimaryButton";
import SecondaryButton from "../components/atoms/SecondaryButton";
import PrimaryText from "../components/atoms/PrimaryText";
```

のようにどんどん行が増えてしまいます。

これを防ぐために

`components/atoms/index.ts` にファイルを作成し

```
export { default as PrimaryButton } from "./PrimaryButton";
....
```

と書くことで下記のように一行で書けるので、こちらに変更してください。

```
import {PrimaryButton, SecondaryButton, PrimaryText} from "../components/atoms";
```

2021-02-12 09:42 UTC, tsurutan commented on src/pages/index.tsx
> +      <main className={styles.main}>
[imo]
ページのでざいんはAtomic Design の template で実装するようにしましょう。

`components/templates/PageTemplate/index.tsx` ですね。

2021-02-14 09:29 UTC, tanakafumiaki commented
以下のように修正いたしました。
tsconfig.jsonにbaseUrlを追加
components/atoms/index.ts作成
components/templates/PageTemplate/index.tsx作成
関数をアロー関数で統一

2021-02-15 08:06 UTC, tsurutan requested changes

2021-02-15 08:06 UTC, tsurutan commented on src/styles/Home.module.sass
> +.main
[imo]
このスタイルは HomeTemplateに対するものだと思うので、 `HomeTemplate/styles.module.sass` に書きましょう。

2021-02-15 08:20 UTC, tanakafumiaki commented
styles.module.sassをtemplate下に作成いたしました。

2021-02-15 10:24 UTC, tsurutan requested changes

2021-02-15 10:24 UTC, tsurutan commented on src/components/atoms/PrimaryButton/index.tsx
> +            <Link href={link}>
[imo]
こちらはButtonというよりもLinkとしての機能になっていると思うので、PrimaryButtonではなくPrimaryLinkになるかなと思います。

また <button> で囲んでいますが、これは不要で

```
<Link href={link}>
  <a className={styles.link}>{text}</a>
</Link>
```

で良いかと思います。

2021-02-15 10:24 UTC, tsurutan commented on src/components/atoms/PrimaryButton/index.tsx
> +export default PrimaryButton
[imo]
文の末尾には `;` を付けるようにしましょう。
他ファイルもいくつかついていない箇所があるので対応お願いします。

またこのようにフォーマットのミスは `eslint` や `prettier` を使用することで防ぐことができるので、次の実装で対応しましょう。

2021-02-15 10:24 UTC, tsurutan commented on src/pages/index.tsx
> +const Home = () => {
[imo]
型を付けましょう。
`Home: React.VFC = () => {`

2021-02-15 15:55 UTC, tanakafumiaki commented
ご指摘の通りPrimaryButtonは機能としてはリンクのため、PrimaryButtonをPrimaryLinkに修正いたしました。
また、関数に型を付与いたしました。

2021-02-16 01:12 UTC, tsurutan commented on src/components/atoms/PrimaryLink/index.tsx
> +    link: string
[imo]
Propsの名前は実際に使用される値に則したほうが良いと思うので `href` が良いと思いました。

2021-02-16 01:12 UTC, tsurutan approved these changes

2021-02-16 01:45 UTC, merged