Feature2021/2/16 create selection page
tanakafumiaki/self-introduction pull request #11
Opened 2021-02-16 14:34 UTC by tanakafumiaki

Selectionページを作成いたしました。
ESLintとPrettierを導入いたしました。

2021-02-17 12:44 UTC, tanakafumiaki commented
<img width="1440" alt="スクリーンショット 2021-02-17 21 42 50" src="https://user-images.githubusercontent.com/38996387/108206012-27e8b900-7169-11eb-81c9-221b9ac77782.png">

2021-02-17 13:02 UTC, tsurutan requested changes

2021-02-17 13:02 UTC, tsurutan commented on src/components/templates/PageTemplate/selection.tsx
> +            <h1 className={styles.title}>
[ask]
こちらのタイトルは他のページでは使用していますか？

2021-02-17 13:02 UTC, tsurutan commented on src/components/templates/PageTemplate/selection.tsx
> +import styles from "src/components/templates/PageTemplate/styles.module.sass";
[imo]
file名は index.tsx にしましょう。

2021-02-17 13:02 UTC, tsurutan commented on src/pages/selection.tsx
> +import SelectionTemplate from "src/components/templates/PageTemplate/selection";
[imo]
import { SelectionTemplate } from "src/components/templates";

と読み込めるようにしましょう。

2021-02-17 13:02 UTC, tsurutan commented on src/pages/selection.tsx
> +import SelectionTemplate from "src/components/templates/PageTemplate/selection";
[imo]
src/pages/selection/index.tsx
という構造にしましょう。

2021-02-17 13:02 UTC, tsurutan commented on src/pages/selection.tsx
> +import SelectionTemplate from "src/components/templates/PageTemplate/selection";
[imo]
tsconfig.json
のcompilerOptionsでbaseUrlを './src' と指定すれば、 './src'以下がrootディレクトリになるので

'components/templates'
と書くことができるます。

2021-02-18 04:52 UTC, tanakafumiaki commented on src/components/templates/PageTemplate/selection.tsx
> +            <h1 className={styles.title}>
全てのページで使用する予定です。

2021-02-18 05:56 UTC, tanakafumiaki commented
ご指摘ありがとうございます。以下の修正を行いました。
1.tsconfig内のbaseUrlを"./"から"./src"に修正
2.SelectionTemplateを作成
3.templatesにindex.tsを追加し、{SelectionTemplate}とimportするように修正
4.pages/selectionをpages/selection/index.tsxに修正

2021-02-18 12:52 UTC, tsurutan commented on src/components/templates/HomeTemplate/index.tsx
> +import styles from "components/templates/HomeTemplate/styles.module.sass";
[imo]
stylesは同じ階層のファイルなので './styles.module.sass' として読み込むと冗長にならないと思います。

2021-02-18 12:52 UTC, tsurutan commented on src/components/templates/PageTemplate/selection.tsx
> +            <h1 className={styles.title}>
であればこちらも atoms として切り出し、再利用できるようにしたほうが良いと思いあmす。

2021-02-18 14:07 UTC, tanakafumiaki commented on src/components/templates/HomeTemplate/index.tsx
> +import styles from "components/templates/HomeTemplate/styles.module.sass";
ご指摘の通りです。ありがとうございます。

2021-02-18 14:11 UTC, tanakafumiaki commented
以下の修正を行いました。
・Titleをatomsへ切り出し
・import文のディレクトリを修正

2021-02-19 10:19 UTC, tsurutan approved these changes
LGTM!!

2021-02-19 11:33 UTC, merged