Profileページの作成
tanakafumiaki/self-introduction pull request #12
Opened 2021-02-20 15:23 UTC by tanakafumiaki

1.「ホーム」ボタンを押下すると「Selection」画面に遷移する
2.マウスオーバーで「ホーム」ボタンが変化する

2021-02-20 15:23 UTC, tanakafumiaki commented
<img width="1440" alt="スクリーンショット 2021-02-21 0 19 41" src="https://user-images.githubusercontent.com/38996387/108600538-0989f400-73db-11eb-85ef-ec910b91deaa.png">

2021-02-20 15:25 UTC, tanakafumiaki commented
写真は、まだ自分自身の写真を用意していなかったため、sampleです。

2021-02-21 08:46 UTC, tsurutan requested changes

2021-02-21 08:46 UTC, tsurutan commented on src/components/atoms/TextBox/index.tsx
> +                    田中史彬(たなかふみあき)です。<br/>
[imo]
このコンポーネントはatoms で最も汎用的なコンポーネントです。
なのでここでテキストを直書きしてしまうと他コンポーネントで使用できなくなります。
なのでこの中身は外部から渡せるようにしましょう。

2021-02-22 01:21 UTC, tanakafumiaki commented
以下の修正を行いました。
atoms_TextBoxにて外部から値を渡すことができるように修正。

2021-02-22 03:11 UTC, tsurutan requested changes

2021-02-22 03:11 UTC, tsurutan commented on src/components/atoms/HomeLink/index.tsx
> +            <a className={styles.link}>Home</a>
[imo]
こちらのコンポーネントもAtomsのため極力汎用化したいので、Homeを直書きしないほうが良いです。
こちらもPropsから渡せるようにしましょう。
またコンポーネントの名前も内容に合わせたものにしたいのですが、すでに `Link` があるため、それと被らないよう適当な名前を付けるべきかなと思います。

2021-02-22 03:11 UTC, tsurutan commented on src/components/atoms/TextBox/index.tsx
> +            <div className={styles.textBox}>
[imo]
propsを渡すときに下記のように ``` で混んで私、styleで `white-space: pre-wrap` を使用すると改行が適用されます。

```js
        <TextBox
          text={
            `
            田中史彬(たなかふみあき)です。
            2018年よりシステムエンジニアとして働いています。
            趣味は自転車です。最近の悩みは運動不足です。
            よろしくお願いいたします！

            email: fumiakishodai@gmail.com`
          }
        />
```

```css
  white-space: pre-wrap;
```

2021-02-22 03:36 UTC, tanakafumiaki commented
以下の修正を行いました。
・HomeLinkコンポーネントを汎用化しCommonLinkに変更
・改行が適用されるように修正

2021-02-22 10:30 UTC, tsurutan approved these changes
LGTM!

2021-02-22 16:14 UTC, merged