Skillsページの作成
tanakafumiaki/self-introduction pull request #13
Opened 2021-02-23 04:46 UTC by tanakafumiaki

1.「ホーム」ボタンを押下すると「Selection」画面に遷移する
2.マウスオーバーで「ホーム」ボタンが変化する

2021-02-23 04:47 UTC, tanakafumiaki commented
<img width="1439" alt="スクリーンショット 2021-02-23 13 42 30" src="https://user-images.githubusercontent.com/38996387/108803273-a4522080-75dd-11eb-9daa-218579496b9c.png">

2021-02-23 13:36 UTC, tsurutan requested changes

2021-02-23 13:36 UTC, tsurutan commented on src/components/atoms/ListBox/index.tsx
> +    itemsList: []
[imo]
itemsで複数形、Listで複数形となり複数形が重なっているのでどちらか一方に合わせましょう。

2021-02-23 13:36 UTC, tsurutan commented on src/components/atoms/ListBox/index.tsx
> +    itemsList: []
[imo]
[]だと型がanyの配列になってしまうので、itemの型を作成し指定しましょう。

2021-02-23 13:36 UTC, tsurutan commented on src/components/atoms/ListBox/index.tsx
> +import styles from './style.module.sass';
[imo]
このコンポーネントはatomsになっていますが、複数の機能を提供しているように思えるので、moleculesへ移したほうが良いかと思います。

2021-02-23 13:36 UTC, tsurutan commented on src/components/atoms/ListBox/index.tsx
> +                {title}
[imo]
この title はリストの要素ではないと思うので、ulの外へ出し pタグで切り出したほうが良いと思います。

2021-02-23 13:36 UTC, tsurutan commented on src/pages/skills/index.tsx
> +const Index: React.VFC = () => {
[imo]
ページ用のコンポーネントはページ名に合わせたほうが良いと思います。
ex: SkillListPage

2021-02-23 23:28 UTC, tanakafumiaki commented
以下の修正を行いました。
・atoms/ListBoxをmolecules下に移動
・pagesの関数をpage名に沿った関数名に修正
・molecules内の変数名をitemsListからitemListに修正し、型を付与

2021-02-24 08:34 UTC, tsurutan requested changes

2021-02-24 08:34 UTC, tsurutan commented on src/components/molecules/ListBox/style.module.sass
> +  .skillsWrapper
[imo]
ネストしてしまうとお互い依存してしまい、メンテナンスが難しくなります。
ネストしないようにクラスはそれぞれ独立して書きましょう。

2021-02-24 08:34 UTC, tsurutan commented on src/pages/skills/index.tsx
> +import {SkillsTemplate} from "components/templates";
[imo]
templateもpageと名前を合わせ
SkillListTemplate としましょう。

2021-02-25 05:05 UTC, tanakafumiaki commented
以下の修正を行いました。
・ネストしていたクラスを独立
・templates名をpages名と合わせる

2021-02-25 13:06 UTC, tsurutan requested changes

2021-02-25 13:06 UTC, tsurutan commented on src/components/templates/SkillListTemplate/styles.module.sass
> +  .skillsWrapper
[imo]
こちらネスとしています。

2021-02-25 14:35 UTC, tanakafumiaki commented on src/components/templates/SkillListTemplate/styles.module.sass
> +  .skillsWrapper
失礼いたしました。
修正いたしました。

2021-02-27 08:01 UTC, tsurutan approved these changes
LGTM!

2021-02-27 08:02 UTC, merged