Productsページの作成
tanakafumiaki/self-introduction pull request #15
Opened 2021-03-01 09:15 UTC by tanakafumiaki

1.「ホーム」ボタンを押下すると「Selection」画面に遷移する
2.マウスオーバーで「ホーム」ボタンが変化する
3.「制作物、URL、概要」をデータの数だけ表示する
4.Gif動画埋め込み

2021-03-01 09:15 UTC, tanakafumiaki commented
<img width="1440" alt="スクリーンショット 2021-03-01 18 11 55" src="https://user-images.githubusercontent.com/38996387/109476322-23ea5e80-7aba-11eb-9554-ac3c292418dc.png">

2021-03-01 12:59 UTC, tsurutan requested changes

2021-03-01 12:59 UTC, tsurutan commented on src/components/atoms/ProductImage/index.tsx
> +            alt="picture"
[imo]
このコンポーネントの汎用性をより上げるため、width, height, alt もpropsから渡せたほうが良いと思います。
また、毎回すべてのpropertyを渡さなくてもよいようにデフォルト値も入れておくと利便性が上がるかと思います。

2021-03-02 02:01 UTC, tanakafumiaki commented
以下の修正を行いました。
・atoms/ProductImageにてpropsから値を渡すことができるよう修正。
・atoms/ProductImageにてimageSrc,width,height,altのデフォルトパラメーターを設定。

2021-03-03 08:26 UTC, tsurutan approved these changes
一点コメントしましたが、こちらを修正でき次第LGTMです。

2021-03-03 08:26 UTC, tsurutan commented on src/components/atoms/ProductImage/index.tsx
> +    imageSrc?: string
[imo]
説明不足で申し訳ございませんが、ImageBoxはimageSrcは渡される前提の atoms だと思うので、このプロパティはoptional でなくて良いと思います。
またデフォルト値も不要です。

2021-03-03 09:10 UTC, tanakafumiaki commented
以下の修正を行いました。
・imageSrcのデフォルト値を削除

2021-03-03 09:10 UTC, merged