add_typescript
tanakafumiaki/self-introduction pull request #9
Opened 2021-02-02 06:23 UTC by tanakafumiaki

TypeScript対応化いたしました。

2021-02-03 08:20 UTC, tsurutan commented on tsconfig.json
> +    "strict": false,
[must]
こちら strict を trueにし strictモードにしてください。

2021-02-03 08:21 UTC, tsurutan requested changes
コメントした内容を反映し、正常にビルドできるか確認お願いします。

2021-02-03 08:21 UTC, tsurutan commented on tsconfig.json
> +    "allowJs": true,
[imo]
allowJsをfalseにし、jsを含まないように対応お願いします。

2021-02-03 15:30 UTC, tanakafumiaki commented on tsconfig.json
> +    "strict": false,
strictモードに変更し、正常にビルドできました。

2021-02-03 15:30 UTC, tanakafumiaki commented on tsconfig.json
> +    "allowJs": true,
allowJsをfalseに変更いたしました。

2021-02-04 08:49 UTC, tsurutan approved these changes
LGTM!

2021-02-05 03:42 UTC, merged